# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acfb761e97dad2f8c0c750d84159f389e56eec8e4500d110becc2c16d9242f65c5b62fa003735a339c66585a6746037527e12dc96c2d3a08123262a64bf8dc84

test:
  secret_key_base: 8373d80fd91c2858c86939e9b7f5d678947fdffc7781a505f5c858b0df2e44e61be60bfdd51d8a570c92351f89c361410861455764d7e80ff8bca02c2208cd04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
